### ISSUE TITLE
kernel compile error

### ISSUE THREAD

**Issue by yusufilker** [150balbes/lib#22]
hello,
I copied your code with git clone command.
I make no changes. my machine  is ubuntu 14.04.
when i run compile sh, u-boot is compiled normally.
during kernel build, I got below errors:

[ error ] ERROR in function compile_kernel [ common.sh:190 ]
[ error ] Kernel was not built [ @host ]
[ o.k. ] Process terminated 

EDIT: More specific information:
`drivers/amlogic/crypto/aml-sha-dma.c: In function ‘aml_sha_update_dma_start’:
drivers/amlogic/crypto/aml-sha-dma.c:426:28: error: ‘final’ may be used uninitialized in this function [-Werror=maybe-uninitialized] return aml_sha_xmit_start(dd, dsc, ctx->fast_nents, final);
cc1: all warnings being treated as errors
make[3]: *** [drivers/amlogic/crypto/aml-sha-dma.o] Error 1
make[2]: *** [drivers/amlogic/crypto] Error 2
make[1]: *** [drivers/amlogic] Error 2`

**Comment by yusufilker** [comment]
solved by initializing variable final = 0
in file aml-sha-dma.c  function "aml_sha_update_dma_start"

I had to disable kernel source download in main.sh. (it downloads old aml-sha-dma.c  )

**Comment by 150balbes** [comment]
Hi What version kernel You are trying to collect (how git is used and which branch) ? To compile correctly you need to properly install the compiler, for example in the directory opt. For each kernel version needs its own version of the compiler. For example, s905x is the version of the compiler, which is written in the file set_make. In this script you can specify the desired directory with the compiler. To build the kernel you can use the script ./set_make , he immediately indicate the right architecture, the directory with the compiler and build command. This script can be freely modified under the current conditions.20.10.2016, 19:49, "yusufilker" <notifications@github.com>:hello,
I copied your code with git clone command.
I make no changes. my machine  is ubuntu 14.04.
when i run compile sh, during kernel build, I got below errors:

[ error ] ERROR in function compile_kernel [ common.sh:190 ]
[ error ] Kernel was not built [ @host ]
[ o.k. ] Process terminated
